# Generated by Django 2.2.4 on 2019-08-19 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_favourite_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
