# Generated by Django 2.2.4 on 2019-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20190820_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='is_mutual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favourite',
            name='mutual_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
