# Generated by Django 2.2.4 on 2019-09-02 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0011_auto_20190822_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_exists', models.BooleanField(default=False)),
                ('thread_started', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.IntegerField(default=0)),
                ('last_message', models.DateTimeField(auto_now_add=True)),
                ('p1_unread', models.IntegerField(default=0)),
                ('p2_unread', models.IntegerField(default=0)),
                ('p1_waves', models.IntegerField(default=0)),
                ('p2_waves', models.IntegerField(default=0)),
                ('p1_initial_wave', models.DateTimeField(auto_now_add=True)),
                ('p2_initial_wave', models.DateTimeField(auto_now_add=True)),
                ('p1_latest_wave', models.DateTimeField(auto_now_add=True)),
                ('p2_latest_wave', models.DateTimeField(auto_now_add=True)),
                ('p1_favourited', models.BooleanField(default=False)),
                ('p1_favourited_date', models.DateTimeField(auto_now_add=True)),
                ('p2_favourited', models.BooleanField(default=False)),
                ('p2_favourited_date', models.DateTimeField(auto_now_add=True)),
                ('mutual_favourites', models.BooleanField(default=False)),
                ('mutual_date', models.DateTimeField(blank=True, null=True)),
                ('p1_views', models.IntegerField(default=0)),
                ('p1_latest_view', models.DateTimeField(auto_now_add=True)),
                ('p2_views', models.IntegerField(default=0)),
                ('p2_latest_view', models.DateTimeField(auto_now_add=True)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_1', to=settings.AUTH_USER_MODEL)),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
