# Generated by Django 2.2.4 on 2019-09-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='last_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p1_favourited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p1_initial_wave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p1_latest_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p1_latest_wave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p2_favourited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p2_initial_wave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p2_latest_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='p2_latest_wave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='thread_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
