# Generated by Django 2.2.4 on 2019-09-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20190903_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.Interaction'),
            preserve_default=False,
        ),
    ]
