# Generated by Django 2.2.4 on 2019-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_interaction_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
