# Generated by Django 2.2.4 on 2020-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20190906_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='list_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
