# Generated by Django 2.2.4 on 2019-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, choices=[('friendship', 'Friendship'), ('fellowship', 'Fellowship'), ('marriage', 'Marriage')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
