# Generated by Django 2.2.4 on 2019-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190810_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='denomination',
            field=models.CharField(blank=True, choices=[('catholic', 'Catholic'), ('anglican', 'Anglican'), ('methodist', 'Methodist'), ('baptist', 'Baptist')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('meat-eater', 'Meat Eater'), ('vegetarian', 'Vegetarian'), ('pescatarian', 'Pescatarian'), ('vegan', 'Vegan'), ('marmite', 'Marmite Only')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('asian', 'Asian')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eyes',
            field=models.CharField(blank=True, choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('grey', 'Grey'), ('other', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hair',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('grey', 'Grey'), ('bald', 'Bald'), ('other', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
