# Generated by Django 2.2.4 on 2019-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190812_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
