# Generated by Django 2.2.4 on 2019-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190812_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
