# Generated by Django 2.2.4 on 2019-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190813_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinks',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_children',
            field=models.CharField(blank=True, choices=[('Yes, living with me', 'Yes, living with me'), ('Yes, living elsewhere', 'Yes, living elsewhere'), ('Yes, but grown-up', 'Yes, but grown-up'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smokes',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Often', 'Often')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wants_children',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('One or Two', 'One or Two'), ('Lots', 'Lots'), ('Undecided', 'Undecided')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('Meat Eater', 'Meat Eater'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Vegan', 'Vegan'), ('Marmite Only', 'Marmite Only')], max_length=25, null=True),
        ),
    ]
