# Generated by Django 2.2.4 on 2019-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190813_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_favourited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='new_waves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_favourited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_waves',
            field=models.IntegerField(default=0),
        ),
    ]
