# Generated by Django 2.2.4 on 2020-05-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('Meat Eater', 'Meat Eater'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Vegan', 'Vegan')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Ethnicity'),
        ),
    ]
