# Generated by Django 2.2.4 on 2020-05-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200505_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gender', to='users.Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sought_gender', to='users.Gender'),
        ),
        migrations.DeleteModel(
            name='LookingFor',
        ),
    ]
