# Generated by Django 2.2.4 on 2020-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200505_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haschildren',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
