# Generated by Django 2.2.4 on 2020-05-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200505_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denomination',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eyes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hair',
            options={},
        ),
        migrations.AlterModelOptions(
            name='haschildren',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='smokes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wantschildren',
            options={},
        ),
    ]
