# Generated by Django 2.2.4 on 2020-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_search'),
        ('users', '0018_auto_20200505_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='denomination',
            field=models.CharField(blank=True, choices=[('Catholic', 'Catholic'), ('Anglican', 'Anglican'), ('Methodist', 'Methodist'), ('Baptist', 'Baptist')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('Meat Eater', 'Meat Eater'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Vegan', 'Vegan'), ('Marmite Only', 'Marmite Only')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='drinks',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Asian', 'Asian')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eyes',
            field=models.CharField(blank=True, choices=[('Brown', 'Brown'), ('Blue', 'Blue'), ('Green', 'Green'), ('Grey', 'Grey'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hair',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Blonde', 'Blonde'), ('Red', 'Red'), ('Grey', 'Grey'), ('Bald', 'Bald'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_children',
            field=models.CharField(blank=True, choices=[('Yes, living with me', 'Yes, living with me'), ('Yes, living elsewhere', 'Yes, living elsewhere'), ('Yes, but grown-up', 'Yes, but grown-up'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Friendship', 'Friendship'), ('Fellowship', 'Fellowship'), ('Marriage', 'Marriage')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smokes',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Often', 'Often')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wants_children',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('One or Two', 'One or Two'), ('Lots', 'Lots'), ('Undecided', 'Undecided')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Denomination',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.DeleteModel(
            name='Eyes',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Hair',
        ),
        migrations.DeleteModel(
            name='HasChildren',
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='Smokes',
        ),
        migrations.DeleteModel(
            name='WantsChildren',
        ),
    ]
