# Generated by Django 2.2.4 on 2019-08-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('in_thread', models.IntegerField(default=0)),
                ('last_message', models.DateTimeField(auto_now_add=True)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_started', to=settings.AUTH_USER_MODEL)),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
