# Generated by Django 2.2.4 on 2019-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20190815_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
