# Generated by Django 2.2.4 on 2019-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_message_read_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
