# Generated by Django 2.2.4 on 2019-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_messagethread_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagethread',
            old_name='unread',
            new_name='p1_unread',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='p2_unread',
            field=models.IntegerField(default=0),
        ),
    ]
