# Generated by Django 2.2.4 on 2019-10-10 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191010_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/support'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
