# Generated by Django 2.2.4 on 2019-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_supportticket_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
