# Generated by Django 2.2.4 on 2019-10-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191010_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='is_active',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=25, null=True),
        ),
    ]
