# Generated by Django 2.2.4 on 2019-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191015_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Awaiting Reply', 'Awaiting Reply'), ('Closed', 'Closed')], default='Active', max_length=15, null=True),
        ),
    ]
