# Generated by Django 2.2.4 on 2019-10-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191015_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='last_message',
            new_name='last_updated',
        ),
    ]
