# Generated by Django 2.2.4 on 2020-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
