# Generated by Django 2.2.4 on 2020-05-03 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.CharField(blank=True, max_length=25, null=True)),
                ('age_low', models.IntegerField(blank=True, null=True)),
                ('age_high', models.IntegerField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, choices=[('Catholic', 'Catholic'), ('Anglican', 'Anglican'), ('Methodist', 'Methodist'), ('Baptist', 'Baptist')], max_length=25, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Asian', 'Asian')], max_length=25, null=True)),
                ('hair', models.CharField(blank=True, choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Blonde', 'Blonde'), ('Red', 'Red'), ('Grey', 'Grey'), ('Bald', 'Bald'), ('Other', 'Other')], max_length=25, null=True)),
                ('eyes', models.CharField(blank=True, choices=[('Brown', 'Brown'), ('Blue', 'Blue'), ('Green', 'Green'), ('Grey', 'Grey'), ('Other', 'Other')], max_length=25, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True)),
                ('looking_for', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Friendship', 'Friendship'), ('Fellowship', 'Fellowship'), ('Marriage', 'Marriage')], max_length=25, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=25, null=True)),
                ('profile_picture', models.BooleanField(default=False)),
                ('intro', models.TextField(blank=True, max_length=100, null=True)),
                ('diet', models.CharField(blank=True, choices=[('Meat Eater', 'Meat Eater'), ('Vegetarian', 'Vegetarian'), ('Pescatarian', 'Pescatarian'), ('Vegan', 'Vegan'), ('Marmite Only', 'Marmite Only')], max_length=25, null=True)),
                ('drinks', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('Often', 'Often')], max_length=25, null=True)),
                ('smokes', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Often', 'Often')], max_length=25, null=True)),
                ('has_children', models.CharField(blank=True, choices=[('Yes, living with me', 'Yes, living with me'), ('Yes, living elsewhere', 'Yes, living elsewhere'), ('Yes, but grown-up', 'Yes, but grown-up'), ('No', 'No')], max_length=25, null=True)),
                ('wants_children', models.CharField(blank=True, choices=[('No', 'No'), ('One or Two', 'One or Two'), ('Lots', 'Lots'), ('Undecided', 'Undecided')], max_length=25, null=True)),
                ('key_words', models.TextField(blank=True, max_length=1000, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='world.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
