# Generated by Django 2.2.4 on 2020-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20200504_2309'),
        ('users', '0018_auto_20200505_0950'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='state',
            field=models.ManyToManyField(related_name='search', to='world.State'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='country',
        ),
        migrations.AddField(
            model_name='search',
            name='country',
            field=models.ManyToManyField(related_name='search', to='world.Country'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='denomination',
        ),
        migrations.AddField(
            model_name='search',
            name='denomination',
            field=models.ManyToManyField(related_name='search', to='users.Denomination'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='diet',
        ),
        migrations.AddField(
            model_name='search',
            name='diet',
            field=models.ManyToManyField(related_name='search', to='users.Diet'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='drinks',
        ),
        migrations.AddField(
            model_name='search',
            name='drinks',
            field=models.ManyToManyField(related_name='search', to='users.Drinks'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='search',
            name='ethnicity',
            field=models.ManyToManyField(related_name='search', to='users.Ethnicity'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='eyes',
        ),
        migrations.AddField(
            model_name='search',
            name='eyes',
            field=models.ManyToManyField(related_name='search', to='users.Eyes'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='gender',
        ),
        migrations.AddField(
            model_name='search',
            name='gender',
            field=models.ManyToManyField(related_name='search_gender', to='users.Gender'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='hair',
        ),
        migrations.AddField(
            model_name='search',
            name='hair',
            field=models.ManyToManyField(related_name='search', to='users.Hair'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='has_children',
        ),
        migrations.AddField(
            model_name='search',
            name='has_children',
            field=models.ManyToManyField(related_name='search', to='users.HasChildren'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='looking_for',
        ),
        migrations.AddField(
            model_name='search',
            name='looking_for',
            field=models.ManyToManyField(related_name='seeking_gender', to='users.Gender'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='search',
            name='marital_status',
            field=models.ManyToManyField(related_name='search', to='users.MaritalStatus'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='relationship',
        ),
        migrations.AddField(
            model_name='search',
            name='relationship',
            field=models.ManyToManyField(related_name='search', to='users.Relationship'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='smokes',
        ),
        migrations.AddField(
            model_name='search',
            name='smokes',
            field=models.ManyToManyField(related_name='search', to='users.Smokes'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='wants_children',
        ),
        migrations.AddField(
            model_name='search',
            name='wants_children',
            field=models.ManyToManyField(related_name='search', to='users.WantsChildren'),
        ),
    ]
