# Generated by Django 2.2.4 on 2020-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200505_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='search', to='world.Country'),
        ),
    ]
