# Generated by Django 2.2.4 on 2020-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200505_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='denomination',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Denomination'),
        ),
        migrations.AlterField(
            model_name='search',
            name='diet',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Diet'),
        ),
        migrations.AlterField(
            model_name='search',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Drinks'),
        ),
        migrations.AlterField(
            model_name='search',
            name='ethnicity',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Ethnicity'),
        ),
        migrations.AlterField(
            model_name='search',
            name='eyes',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Eyes'),
        ),
        migrations.AlterField(
            model_name='search',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='search_gender', to='users.Gender'),
        ),
        migrations.AlterField(
            model_name='search',
            name='hair',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Hair'),
        ),
        migrations.AlterField(
            model_name='search',
            name='has_children',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.HasChildren'),
        ),
        migrations.AlterField(
            model_name='search',
            name='looking_for',
            field=models.ManyToManyField(blank=True, related_name='seeking_gender', to='users.Gender'),
        ),
        migrations.AlterField(
            model_name='search',
            name='marital_status',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='search',
            name='relationship',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Relationship'),
        ),
        migrations.AlterField(
            model_name='search',
            name='smokes',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.Smokes'),
        ),
        migrations.AlterField(
            model_name='search',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='search', to='world.State'),
        ),
        migrations.AlterField(
            model_name='search',
            name='wants_children',
            field=models.ManyToManyField(blank=True, related_name='search', to='users.WantsChildren'),
        ),
    ]
