# Generated by Django 2.2.4 on 2020-05-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200505_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
